"use client";

import { useEffect, useMemo, useState } from "react";
import { Calendar, Download, FileText, Loader2, Trash2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { apiFetch } from "@/lib/api-client";

type ReportStatus = "Ready" | "Failed";
type DateRange = "7d" | "30d" | "all";
type ReportTypeFilter = "All" | "Executive" | "Analyst";

interface GeneratedReport {
    id: string;
    name: string;
    type: "Executive" | "Analyst";
    created_at: string;
    size_kb: string;
    status: ReportStatus;
    dataset_id: number;
    summary: string;
    key_insights: string[];
    recommendations: string[];
    risks: string[];
    drivers: string[];
    kpis: Record<string, string>;
}

interface OverviewResponse {
    dataset_id?: number;
    total_rows: number;
    total_columns: number;
    analyst_insights?: {
        executive_summary?: string;
        recommendations?: string[];
        alerts?: Array<{ title: string; description: string; severity: string }>;
        key_drivers?: {
            positive_drivers?: Array<{ driver: string; impact: number; metric: string }>;
            negative_drivers?: Array<{ driver: string; impact: number; metric: string }>;
        };
        business_summary?: {
            total_revenue?: number | null;
            total_cost?: number | null;
            total_profit?: number | null;
            profit_margin_pct?: number | null;
        };
    } | null;
}

interface AISummaryResponse {
    summary: string;
    key_insights: string[];
}

const REPORTS_STORAGE_KEY = "smartsheet_reports_v1";

function loadReports(): GeneratedReport[] {
    if (typeof window === "undefined") return [];
    try {
        const raw = localStorage.getItem(REPORTS_STORAGE_KEY);
        if (!raw) return [];
        const parsed = JSON.parse(raw);
        if (!Array.isArray(parsed)) return [];
        return parsed.map((report) => ({
            ...report,
            risks: Array.isArray(report?.risks) ? report.risks : [],
            drivers: Array.isArray(report?.drivers) ? report.drivers : [],
            kpis: report?.kpis && typeof report.kpis === "object" ? report.kpis : {},
        }));
    } catch {
        return [];
    }
}

function saveReports(reports: GeneratedReport[]): void {
    if (typeof window === "undefined") return;
    localStorage.setItem(REPORTS_STORAGE_KEY, JSON.stringify(reports));
}

function buildReportMarkdown(report: GeneratedReport): string {
    const lines: string[] = [];
    lines.push(`# ${report.name}`);
    lines.push("");
    lines.push(`- Report ID: ${report.id}`);
    lines.push(`- Dataset ID: ${report.dataset_id}`);
    lines.push(`- Type: ${report.type}`);
    lines.push(`- Generated: ${new Date(report.created_at).toLocaleString()}`);
    lines.push("");
    lines.push("## Executive Summary");
    lines.push(report.summary || "No summary available.");
    lines.push("");
    lines.push("## Key Insights");
    if (report.key_insights.length === 0) {
        lines.push("- No insights available.");
    } else {
        report.key_insights.forEach((item) => lines.push(`- ${item}`));
    }
    lines.push("");
    lines.push("## KPI Snapshot");
    if (Object.keys(report.kpis).length === 0) {
        lines.push("- KPI snapshot unavailable.");
    } else {
        Object.entries(report.kpis).forEach(([key, value]) => lines.push(`- ${key}: ${value}`));
    }
    lines.push("");
    lines.push("## Risk Alerts");
    if (report.risks.length === 0) {
        lines.push("- No major risks detected.");
    } else {
        report.risks.forEach((item) => lines.push(`- ${item}`));
    }
    lines.push("");
    lines.push("## Driver Highlights");
    if (report.drivers.length === 0) {
        lines.push("- No key drivers available.");
    } else {
        report.drivers.forEach((item) => lines.push(`- ${item}`));
    }
    lines.push("");
    lines.push("## Recommendations");
    if (report.recommendations.length === 0) {
        lines.push("- No recommendations available.");
    } else {
        report.recommendations.forEach((item) => lines.push(`- ${item}`));
    }
    lines.push("");
    lines.push("---");
    lines.push("Generated by SmartSheet");
    return lines.join("\n");
}

function estimateSizeKb(text: string): string {
    const bytes = new Blob([text]).size;
    return `${(bytes / 1024).toFixed(1)} KB`;
}

function inRange(dateIso: string, range: DateRange): boolean {
    if (range === "all") return true;
    const now = Date.now();
    const created = new Date(dateIso).getTime();
    if (Number.isNaN(created)) return false;
    const days = range === "7d" ? 7 : 30;
    return (now - created) <= days * 24 * 60 * 60 * 1000;
}

export default function ReportsPage() {
    const [reports, setReports] = useState<GeneratedReport[]>([]);
    const [generating, setGenerating] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [typeFilter, setTypeFilter] = useState<ReportTypeFilter>("All");
    const [dateRange, setDateRange] = useState<DateRange>("30d");

    useEffect(() => {
        setReports(loadReports());
    }, []);

    const filteredReports = useMemo(
        () =>
            reports.filter((report) => {
                const typeMatch = typeFilter === "All" || report.type === typeFilter;
                return typeMatch && inRange(report.created_at, dateRange);
            }),
        [reports, typeFilter, dateRange]
    );

    const persistReports = (next: GeneratedReport[]) => {
        setReports(next);
        saveReports(next);
    };

    const generateReport = async () => {
        setGenerating(true);
        setError(null);
        try {
            const latestRes = await apiFetch("/datasets/latest");
            if (!latestRes.ok) {
                throw new Error("No dataset found. Upload a CSV first.");
            }
            const latest = await latestRes.json();
            const datasetId = Number(latest?.id);
            const datasetName = String(latest?.name || "Dataset");
            if (!Number.isFinite(datasetId)) {
                throw new Error("Invalid dataset id returned by API.");
            }

            const overviewRes = await apiFetch("/overview/metrics");
            if (!overviewRes.ok) {
                throw new Error("Unable to load overview metrics.");
            }
            const overview: OverviewResponse = await overviewRes.json();

            let summaryPayload: AISummaryResponse | null = null;
            const summaryRes = await apiFetch("/ai/summarize", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ dataset_id: datasetId }),
            });
            if (summaryRes.ok) {
                summaryPayload = await summaryRes.json();
            }

            const summary = summaryPayload?.summary
                || overview?.analyst_insights?.executive_summary
                || "Summary unavailable.";
            const keyInsights = summaryPayload?.key_insights || [];
            const recommendations = overview?.analyst_insights?.recommendations || [];
            const risks = (overview?.analyst_insights?.alerts || [])
                .slice(0, 5)
                .map((alert) => `[${String(alert.severity).toUpperCase()}] ${alert.title}: ${alert.description}`);

            const positiveDrivers = overview?.analyst_insights?.key_drivers?.positive_drivers || [];
            const negativeDrivers = overview?.analyst_insights?.key_drivers?.negative_drivers || [];
            const drivers = [
                ...positiveDrivers.slice(0, 3).map(
                    (item) => `Positive: ${item.driver} (${item.metric} ${item.impact.toLocaleString(undefined, { maximumFractionDigits: 2 })})`
                ),
                ...negativeDrivers.slice(0, 3).map(
                    (item) => `Negative: ${item.driver} (${item.metric} ${item.impact.toLocaleString(undefined, { maximumFractionDigits: 2 })})`
                ),
            ];

            const business = overview?.analyst_insights?.business_summary;
            const kpis: Record<string, string> = {};
            if (typeof business?.total_revenue === "number") kpis["Total Revenue"] = business.total_revenue.toLocaleString(undefined, { maximumFractionDigits: 0 });
            if (typeof business?.total_cost === "number") kpis["Total Cost"] = business.total_cost.toLocaleString(undefined, { maximumFractionDigits: 0 });
            if (typeof business?.total_profit === "number") kpis["Total Profit"] = business.total_profit.toLocaleString(undefined, { maximumFractionDigits: 0 });
            if (typeof business?.profit_margin_pct === "number") kpis["Profit Margin %"] = business.profit_margin_pct.toFixed(2);

            const tempReport: GeneratedReport = {
                id: `${Date.now()}`,
                name: `${datasetName} - ${new Date().toLocaleDateString()} Report`,
                type: "Executive",
                created_at: new Date().toISOString(),
                size_kb: "0.0 KB",
                status: "Ready",
                dataset_id: datasetId,
                summary,
                key_insights: keyInsights,
                recommendations,
                risks,
                drivers,
                kpis,
            };

            const markdown = buildReportMarkdown(tempReport);
            const report: GeneratedReport = {
                ...tempReport,
                size_kb: estimateSizeKb(markdown),
            };

            persistReports([report, ...reports]);
        } catch (e) {
            const message = e instanceof Error ? e.message : "Failed to generate report.";
            setError(message);
        } finally {
            setGenerating(false);
        }
    };

    const downloadReport = (report: GeneratedReport) => {
        const markdown = buildReportMarkdown(report);
        const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const anchor = document.createElement("a");
        anchor.href = url;
        const safeName = report.name.replace(/[^a-z0-9-_]+/gi, "_").toLowerCase();
        anchor.download = `${safeName || "report"}.md`;
        document.body.appendChild(anchor);
        anchor.click();
        anchor.remove();
        URL.revokeObjectURL(url);
    };

    const downloadReportPdf = async (report: GeneratedReport) => {
        const { jsPDF } = await import("jspdf");
        const doc = new jsPDF({ unit: "pt", format: "a4" });
        const marginX = 48;
        const marginY = 56;
        const maxWidth = doc.internal.pageSize.getWidth() - marginX * 2;
        const maxHeight = doc.internal.pageSize.getHeight() - marginY;
        const lines = doc.splitTextToSize(buildReportMarkdown(report), maxWidth);

        let y = marginY;
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);

        for (const line of lines) {
            if (y > maxHeight) {
                doc.addPage();
                y = marginY;
            }
            doc.text(String(line), marginX, y);
            y += 14;
        }

        const safeName = report.name.replace(/[^a-z0-9-_]+/gi, "_").toLowerCase();
        doc.save(`${safeName || "report"}.pdf`);
    };

    const deleteReport = (reportId: string) => {
        const next = reports.filter((report) => report.id !== reportId);
        persistReports(next);
    };

    return (
        <div className="flex flex-col gap-6 h-full animate-in fade-in zoom-in-95 duration-500">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold tracking-tight">Reports</h1>
                    <p className="text-muted-foreground">Generate downloadable analyst reports from your latest CSV.</p>
                </div>
                <button
                    onClick={generateReport}
                    disabled={generating}
                    className="bg-primary text-primary-foreground px-4 py-2 rounded-lg text-sm font-medium hover:bg-primary/90 transition-colors shadow-sm flex items-center gap-2 disabled:opacity-60"
                >
                    {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileText className="w-4 h-4" />}
                    {generating ? "Generating..." : "Generate Report"}
                </button>
            </div>
            {error && (
                <div className="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive">
                    {error}
                </div>
            )}

            <div className="bg-card/50 backdrop-blur-sm border border-border/50 rounded-xl overflow-hidden shadow-sm flex-1 min-h-0">
                <div className="p-4 border-b border-border/50 flex flex-wrap items-center gap-2">
                    <select
                        value={typeFilter}
                        onChange={(e) => setTypeFilter(e.target.value as ReportTypeFilter)}
                        className="px-3 py-1.5 text-sm bg-secondary border border-border/50 rounded-md"
                    >
                        <option value="All">All Types</option>
                        <option value="Executive">Executive</option>
                        <option value="Analyst">Analyst</option>
                    </select>
                    <button
                        onClick={() => setDateRange(dateRange === "30d" ? "all" : "30d")}
                        className="px-3 py-1.5 text-sm font-medium bg-secondary text-secondary-foreground rounded-md flex items-center gap-2"
                    >
                        <Calendar className="w-3.5 h-3.5" />
                        {dateRange === "all" ? "All Time" : "Last 30 Days"}
                    </button>
                </div>

                <div className="overflow-x-auto">
                    {filteredReports.length === 0 ? (
                        <div className="p-8 text-center text-sm text-muted-foreground">
                            No reports found for the selected filter.
                        </div>
                    ) : (
                        <table className="w-full text-sm text-left">
                            <thead className="text-xs text-muted-foreground uppercase bg-secondary/50">
                                <tr>
                                    <th className="px-6 py-3">Report Name</th>
                                    <th className="px-6 py-3">Type</th>
                                    <th className="px-6 py-3">Date</th>
                                    <th className="px-6 py-3">Size</th>
                                    <th className="px-6 py-3">Status</th>
                                    <th className="px-6 py-3 text-right">Actions</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-border/50">
                                {filteredReports.map((report) => (
                                    <tr key={report.id} className="hover:bg-muted/50 transition-colors group">
                                        <td className="px-6 py-4 font-medium flex items-center gap-3">
                                            <div className="p-2 bg-primary/10 rounded-lg text-primary">
                                                <FileText className="w-4 h-4" />
                                            </div>
                                            <div>
                                                <p>{report.name}</p>
                                                <p className="text-xs text-muted-foreground">Dataset #{report.dataset_id}</p>
                                            </div>
                                        </td>
                                        <td className="px-6 py-4 text-muted-foreground">{report.type}</td>
                                        <td className="px-6 py-4 text-muted-foreground">
                                            {new Date(report.created_at).toLocaleString()}
                                        </td>
                                        <td className="px-6 py-4 text-muted-foreground">{report.size_kb}</td>
                                        <td className="px-6 py-4">
                                            <span
                                                className={cn(
                                                    "px-2 py-1 rounded-full text-xs font-medium",
                                                    report.status === "Ready"
                                                        ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                                                        : "bg-destructive/10 text-destructive"
                                                )}
                                            >
                                                {report.status}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <div className="inline-flex items-center gap-1">
                                                <button
                                                    onClick={() => downloadReport(report)}
                                                    className="text-muted-foreground hover:text-primary transition-colors p-2 hover:bg-secondary rounded-md"
                                                    title="Download Markdown"
                                                >
                                                    <Download className="w-4 h-4" />
                                                </button>
                                                <button
                                                    onClick={() => downloadReportPdf(report)}
                                                    className="text-muted-foreground hover:text-primary transition-colors p-2 hover:bg-secondary rounded-md"
                                                    title="Download PDF"
                                                >
                                                    <FileText className="w-4 h-4" />
                                                </button>
                                                <button
                                                    onClick={() => deleteReport(report.id)}
                                                    className="text-muted-foreground hover:text-destructive transition-colors p-2 hover:bg-secondary rounded-md"
                                                    title="Delete"
                                                >
                                                    <Trash2 className="w-4 h-4" />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    )}
                </div>
            </div>
        </div>
    );
}
